In [ ]:
import numpy as np

In [ ]:
dataset = np.array([[7000,45],[6000,44],[52000,40]])
dataset

array([[ 7000,    45],
       [ 6000,    44],
       [52000,    40]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [ ]:
norm_dataset = scaler.fit_transform(dataset)
norm_dataset

array([[0.02173913, 1.        ],
       [0.        , 0.8       ],
       [1.        , 0.        ]])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler2 = StandardScaler()

In [ ]:
std_dataset = scaler2.fit_transform(dataset)
std_dataset

array([[-0.68367174,  0.9258201 ],
       [-0.73028572,  0.46291005],
       [ 1.41395746, -1.38873015]])

In [ ]:
matriks_awal = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
matriks_awal

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(matriks_awal, test_size=0.2 ,random_state=1)
print ('training set=')
print (train_set)
print('test set=')
print(test_set)

training set=
[[7 8 9]
 [4 5 6]]
test set=
[[1 2 3]]
