In [2]:
#import library numpy
import numpy as np

In [3]:
#untuk mengetahui panjang array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [5]:
#flattening
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [6]:
#reshape
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,4)
newarr1= arr.reshape(2,2,-1)
print(newarr)
print(newarr1)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
##sorting array
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [9]:
arr = np.array([41,42,43,44,45])
x = [True,False,True,False,True]
newarr = arr[x]
print(newarr)

[41 43 45]


In [10]:
##gabung 2 array
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [11]:
##array split
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [12]:
## searching array
arr=np.array([1,2,3,4,5,4,4,2,1,2])
x = np.where(arr==4)
print(x)

(array([3, 5, 6]),)


In [13]:
#menggunakan step
my_list = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
print(my_list[6:0:-1])

[4, 5, 6, 7, 8, 9]


In [14]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]
