## Import library

In [ ]:
#Menampilkan Drive
from google.colab import drive
drive.mount("/content/gdrive")

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

## Import dataset

In [ ]:
dataset = pd.read_csv('/content/gdrive/MyDrive/Python TIA/ml-1m/DataListrik.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [ ]:
y_train=y_train.reshape(len(y_train),1)
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


## Feature scalling standardscale

In [ ]:
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train= sc_y.fit_transform(y_train)


In [ ]:
print(X_train)

[[-1.13572795 -0.88685592  0.67357894  0.52070558]
 [-0.80630243 -0.00971567  0.45145467  0.14531044]
 [ 1.77128416  1.84743445  0.24279248 -1.88374143]
 ...
 [-0.38409993 -1.24886277  0.84522042  0.13092486]
 [-0.9232821  -1.04155299  1.54693117  0.8830852 ]
 [ 1.70136528  1.05824381 -1.20438076 -2.42285818]]


In [ ]:
print(y_train)

[[ 1.15069786]
 [ 0.79540777]
 [-1.30936356]
 ...
 [ 0.27595724]
 [ 0.49346982]
 [-1.53508417]]


## Training the SVR model on the Training set

In [ ]:
regressor = SVR(kernel='rbf')
#X,y disini adalah X,y yang sudah mengalami transformasi scalling
regressor.fit(X_train,y_train)

D:\anaconda\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [ ]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


In [ ]:
y_test_scale = sc_y.transform(y_test.reshape(-1,1))
y_pred_scale = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)).reshape(-1,1))
y_test_scale = y_test.reshape(len(y_test),1)
#print(sc_y.inverse_transform(regressor.predict(sc_X.transform([[6.5]])).reshape(-1,1))) #hasilnya menjadi yg adad di feature scalling




In [ ]:
print(y_test_scale)

[[431.23]
 [460.01]
 [461.14]
 ...
 [473.26]
 [438.  ]
 [463.28]]


In [ ]:
print(y_pred_scale)

[[434.05242921]
 [457.93810186]
 [461.03113894]
 ...
 [470.60268461]
 [439.41653548]
 [460.91757115]]


In [ ]:
print(y_test_scale)

[[431.23]
 [460.01]
 [461.14]
 ...
 [473.26]
 [438.  ]
 [463.28]]


## Predicting the Test set results

In [ ]:
print(np.concatenate((y_pred_scale,y_test_scale),1))

[[434.05242921 431.23      ]
 [457.93810186 460.01      ]
 [461.03113894 461.14      ]
 ...
 [470.60268461 473.26      ]
 [439.41653548 438.        ]
 [460.91757115 463.28      ]]


## Evaluating the Model Performance

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test_scale, y_pred_scale)

0.948078404998626